# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Set a working directory
WORKDIR /app

# Copy all files to the container
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir fastmcp google-api-python-client python-dotenv

# Set environment variables placeholders (they will be overridden by startCommand config)
ENV GOOGLE_API_KEY=changeme
ENV GOOGLE_CSE_ID=changeme

# Command to run the MCP server
CMD ["python", "google_search_mcp_server.py"]
